app:
  upload-dir: uploads/faces/
  face-verification-threshold: 0.6
  max-login-attempts: 3
  login-attempt-timeout: 300
  jwt-secret: ${JWT_SECRET:your-secret-key-here}
  jwt-expiration: 86400000

spring:
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=600s

logging:
  level:
    com.trustvote.votacao: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 